# Site settings
author: Maria Galdina
title: Data Science Bootcamp journey
header-img: img/home-bg.png
email: mari.galdina@gmail.com
copyright_name: Maria Galdina
description: > # this means to ignore newlines until "baseurl:"
  What we can learn?
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  fts-tech

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
